services:
  - type: web
    name: musicwave-api
    env: node
    repo: https://github.com/greatdaveo/MusicWave
    branch: master
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: JWT_SECRET
        value: ${JWT_SECRET}